packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@tailwindcss/oxide": false
  esbuild: false
  lefthook: false
  sharp: false
  workerd: false
overrides:
  "@reatom/core": "3.10.3"
  "@tiptap/core": "3.10.5"
  "@tiptap/extensions": "3.10.5"
